on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

name: Continuous Integration
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - uses: actions/setup-node@v2
        name: Use Node.js
        with:
          node-version: '14'
          cache: 'npm'

      - run: npm install
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - uses: actions/setup-node@v2
        name: Use Node.js
        with:
          node-version: '14'
          cache: 'npm'

      - run: sudo apt-get install sqlite3
      - run: npm install nyc sequelize-cli
      - run: npm install
      - run: npm run test
      - run: npm run coverage

      - name: Publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
